stages:
        - build
        - style
        - test
        - deploy

building:
        stage: build
        tags: 
                - build
        script:
                - cd src/cat/
                - make s21_cat
                - cd ../grep/
                - make s21_grep
        artifacts:
                paths:
                        - src/cat/s21_cat
                        - src/grep/s21_grep
                expire_in: 30 days
        after_script:
                - sh src/notify.sh "build" 
styletest:
        stage: style
        tags:
                - style
        script:
                - cd src/
                - bash style_test.sh
        when: always
        after_script:
                - sh src/notify.sh "style" 

testing:
        stage: test
        tags:
                - test
        script:
                - cd src/
                - sudo chmod +x test.sh
                - bash test.sh 
        when: on_success
        after_script:
                - sh src/notify.sh "test" 

deploying:
        stage: deploy
        tags:
                - deploy
        script:
                - cd src
                - sudo chmod +x deploy.sh
                - bash deploy.sh 
        when: manual
        after_script:
                - sh src/notify.sh "deploy" 